import type { BankEntry } from '../../../types/trivia'
import { q } from './entry'

/** Clubs, stadiums, nicknames and rivalries. */
export const clubs: BankEntry[] = [
  q('Which club plays its home games at Old Trafford?', 'Manchester United', ['Manchester City', 'Liverpool', 'Leeds United'], 'easy'),
  q('Old Trafford is known by which nickname?', 'The Theatre of Dreams', ['The Cathedral', 'The Fortress', 'The Home of Football'], 'medium'),
  q('Which club plays at the Camp Nou?', 'Barcelona', ['Real Madrid', 'Atlético Madrid', 'Valencia'], 'easy'),
  q('Which club plays at the Santiago Bernabéu?', 'Real Madrid', ['Barcelona', 'Sevilla', 'Real Betis'], 'easy'),
  q('Which club plays its home games at Anfield?', 'Liverpool', ['Everton', 'Manchester United', 'Newcastle United'], 'easy'),
  q('"You’ll Never Walk Alone" is the anthem of which English club?', 'Liverpool', ['Manchester United', 'West Ham United', 'Celtic'], 'easy'),
  q('The San Siro stadium in Milan is shared by AC Milan and which other club?', 'Inter Milan', ['Juventus', 'Atalanta', 'Monza'], 'medium'),
  q('Which club plays at the Allianz Arena?', 'Bayern Munich', ['Borussia Dortmund', 'Schalke 04', 'RB Leipzig'], 'easy'),
  q('Borussia Dortmund’s famous standing terrace is known as what?', 'The Yellow Wall', ['The Black Bloc', 'The South Curve', 'The Bee Hive'], 'medium'),
  q('Arsenal left Highbury in 2006 to move into which stadium?', 'The Emirates Stadium', ['Wembley', 'The London Stadium', 'Stamford Bridge'], 'medium'),
  q('Which club plays its home games at Stamford Bridge?', 'Chelsea', ['Fulham', 'Arsenal', 'Tottenham Hotspur'], 'easy'),
  q('Which club plays at the Etihad Stadium?', 'Manchester City', ['Manchester United', 'Aston Villa', 'Newcastle United'], 'easy'),
  q('Which club plays at the Parc des Princes in Paris?', 'PSG', ['Marseille', 'Lyon', 'Monaco'], 'medium'),
  q('The Maracanã, one of football’s most famous stadiums, is in which city?', 'Rio de Janeiro', ['São Paulo', 'Buenos Aires', 'Brasília'], 'medium'),
  q('Which national stadium in London is famous for its giant arch?', 'Wembley', ['Twickenham', 'The Emirates', 'The London Stadium'], 'easy'),
  q('La Bombonera is the iconic home of which Argentine club?', 'Boca Juniors', ['River Plate', 'Racing Club', 'Independiente'], 'medium'),
  q('El Monumental, Argentina’s largest stadium, is home to which club?', 'River Plate', ['Boca Juniors', 'San Lorenzo', 'Vélez Sarsfield'], 'hard'),
  q('The Superclásico is the fierce derby between Boca Juniors and which club?', 'River Plate', ['Racing Club', 'Independiente', 'Estudiantes'], 'medium'),
  q('Which Mexican stadium is the only one to have hosted two World Cup finals?', 'Estadio Azteca', ['Estadio Olímpico', 'Estadio Jalisco', 'Estadio BBVA'], 'hard'),
  q('Manchester United are known by which nickname?', 'The Red Devils', ['The Reds', 'The Red Army', 'The United'], 'easy'),
  q('Arsenal are known by which nickname?', 'The Gunners', ['The Hammers', 'The Blades', 'The Cannons'], 'easy'),
  q('Newcastle United are known by which nickname?', 'The Magpies', ['The Toon Tigers', 'The Geordies', 'The Miners'], 'medium'),
  q('Juventus are affectionately known as what in Italy?', 'The Old Lady', ['The Old Guard', 'The Grand Duchess', 'The Black Queen'], 'medium'),
  q('Real Madrid’s star-studded early-2000s signing policy gave the squad what nickname?', 'The Galácticos', ['The Millonarios', 'The Estrellas', 'The Blancos Reales'], 'medium'),
  q('What is Barcelona’s famous club motto?', 'Més que un club', ['Visca el Barça', 'Força Barça', 'Un club, un país'], 'medium'),
  q('Ajax are based in which city?', 'Amsterdam', ['Rotterdam', 'Eindhoven', 'Utrecht'], 'medium'),
  q('Bayern Munich come from which German region?', 'Bavaria', ['Saxony', 'Rhineland', 'Prussia'], 'easy'),
  q('Boca Juniors and River Plate are both from which city?', 'Buenos Aires', ['Rosario', 'Córdoba', 'Montevideo'], 'medium'),
  q('Pelé spent almost his entire club career at which Brazilian club?', 'Santos', ['Flamengo', 'Corinthians', 'São Paulo'], 'medium'),
  q('Which Italian club renamed its stadium after Diego Maradona in 2020?', 'Napoli', ['Roma', 'Lazio', 'Fiorentina'], 'medium'),
  q('The Stade Vélodrome is home to which French club?', 'Marseille', ['PSG', 'Lyon', 'Nice'], 'hard'),
  q('Celtic Park and Ibrox are rival stadiums in which city?', 'Glasgow', ['Edinburgh', 'Dundee', 'Aberdeen'], 'medium'),
  q('Benfica play their home games at which stadium?', 'Estádio da Luz', ['Estádio do Dragão', 'Estádio José Alvalade', 'Estádio Nacional'], 'hard'),
  q('Porto play their home games at which stadium?', 'Estádio do Dragão', ['Estádio da Luz', 'Estádio do Bessa', 'Estádio Municipal'], 'hard'),
  q('What is Inter Milan’s full club name?', 'Internazionale', ['International Milan', 'Internazionale Lombardia', 'Inter Calcio'], 'medium'),
  q('Sporting CP, boyhood club of Cristiano Ronaldo, is based in which city?', 'Lisbon', ['Porto', 'Braga', 'Coimbra'], 'medium'),
  q('The Intercontinental Derby between Galatasaray and Fenerbahçe takes place in which city?', 'Istanbul', ['Ankara', 'Izmir', 'Bursa'], 'medium'),
  q('Which Egyptian club has won the most CAF Champions League titles?', 'Al Ahly', ['Zamalek', 'Espérance', 'Wydad Casablanca'], 'hard'),
  q('David Beckham left Real Madrid in 2007 to join which MLS club?', 'LA Galaxy', ['Inter Miami', 'New York Red Bulls', 'LAFC'], 'medium'),
  q('AC Milan is spelled "Milan" rather than "Milano" because the club was founded by people from which country?', 'England', ['France', 'Switzerland', 'Austria'], 'hard'),
  q('The "Real" in Real Madrid was granted by a Spanish king and means what?', 'Royal', ['True', 'Great', 'Noble'], 'medium'),
  q('Which Madrid club moved into the Metropolitano stadium in 2017?', 'Atlético Madrid', ['Real Madrid', 'Rayo Vallecano', 'Getafe'], 'hard'),
  q('Anfield and Goodison Park, homes of Liverpool and Everton, are separated by what?', 'Stanley Park', ['The River Mersey', 'A railway line', 'The M62 motorway'], 'hard'),
  q('Ajax, PSV and which other club make up the traditional "big three" of Dutch football?', 'Feyenoord', ['AZ Alkmaar', 'FC Twente', 'FC Utrecht'], 'hard'),
  q('Which London club plays its home games at the London Stadium, built for the 2012 Olympics?', 'West Ham United', ['Crystal Palace', 'Millwall', 'Charlton Athletic'], 'medium'),
  q('Tottenham Hotspur’s club emblem features which animal?', 'A cockerel', ['A lion', 'An eagle', 'A stag'], 'medium'),
  q('Which club’s badge features a liver bird?', 'Liverpool', ['Everton', 'Norwich City', 'Cardiff City'], 'medium'),
  q('Flamengo, one of the world’s most supported clubs, is based in which country?', 'Brazil', ['Portugal', 'Argentina', 'Colombia'], 'medium'),
  q('Which German club is famous for its fan-owned "50+1" culture and plays in yellow and black?', 'Borussia Dortmund', ['Bayern Munich', 'Eintracht Frankfurt', 'Wolfsburg'], 'easy'),
]
