import type { BankEntry } from '../../../types/trivia'
import { q } from './entry'

/** Champions League / European Cup and other UEFA club competitions. */
export const europeanCups: BankEntry[] = [
  q('Which club has won the most European Cup / Champions League titles?', 'Real Madrid', ['AC Milan', 'Bayern Munich', 'Liverpool'], 'easy'),
  q('Which club won the first five European Cups from 1956 to 1960?', 'Real Madrid', ['Benfica', 'AC Milan', 'Ajax'], 'hard'),
  q('In which year was the European Cup rebranded as the UEFA Champions League?', '1992', ['1990', '1995', '1988'], 'medium'),
  q('Who scored Manchester United’s injury-time winner in the 1999 Champions League final?', 'Ole Gunnar Solskjær', ['Teddy Sheringham', 'Dwight Yorke', 'Andy Cole'], 'medium'),
  q('Which club did Manchester United beat in the dramatic 1999 Champions League final?', 'Bayern Munich', ['Juventus', 'Real Madrid', 'AC Milan'], 'medium'),
  q('In the 2005 "Miracle of Istanbul" final, Liverpool came back from how many goals down against AC Milan?', '3', ['2', '1', '4'], 'medium'),
  q('Which club has won the second-most European Cup / Champions League titles with 7?', 'AC Milan', ['Bayern Munich', 'Liverpool', 'Barcelona'], 'medium'),
  q('Who is the all-time top scorer in the Champions League?', 'Cristiano Ronaldo', ['Lionel Messi', 'Robert Lewandowski', 'Karim Benzema'], 'easy'),
  q('Which was the first English club to win the European Cup, in 1968?', 'Manchester United', ['Liverpool', 'Nottingham Forest', 'Arsenal'], 'medium'),
  q('Celtic’s "Lisbon Lions" became the first British club to win the European Cup in which year?', '1967', ['1970', '1965', '1972'], 'medium'),
  q('Which English club won back-to-back European Cups in 1979 and 1980?', 'Nottingham Forest', ['Liverpool', 'Aston Villa', 'Leeds United'], 'medium'),
  q('Which unfancied English club won the European Cup in 1982?', 'Aston Villa', ['Everton', 'West Ham United', 'Ipswich Town'], 'hard'),
  q('Chelsea won their first Champions League in 2012 by beating which club in its own stadium?', 'Bayern Munich', ['Borussia Dortmund', 'Real Madrid', 'Barcelona'], 'medium'),
  q('Who scored Chelsea’s late equaliser and the winning penalty in the 2012 Champions League final?', 'Didier Drogba', ['Frank Lampard', 'Fernando Torres', 'Juan Mata'], 'medium'),
  q('Pep Guardiola’s Barcelona beat which club in both the 2009 and 2011 Champions League finals?', 'Manchester United', ['Chelsea', 'Bayern Munich', 'Arsenal'], 'medium'),
  q('Whose stunning left-footed volley won the 2002 Champions League final for Real Madrid?', 'Zinedine Zidane', ['Raúl', 'Luís Figo', 'Roberto Carlos'], 'medium'),
  q('Real Madrid’s long-awaited tenth European crown in 2014 is known by what Spanish name?', 'La Décima', ['La Doblete', 'El Décimo Rey', 'La Gran Copa'], 'medium'),
  q('Who scored Real Madrid’s 93rd-minute equaliser in the 2014 Champions League final against Atlético?', 'Sergio Ramos', ['Cristiano Ronaldo', 'Gareth Bale', 'Karim Benzema'], 'medium'),
  q('Which club won three consecutive Champions League titles from 2016 to 2018?', 'Real Madrid', ['Barcelona', 'Bayern Munich', 'Atlético Madrid'], 'medium'),
  q('Who scored a spectacular overhead kick for Real Madrid in the 2018 final against Liverpool?', 'Gareth Bale', ['Cristiano Ronaldo', 'Karim Benzema', 'Marco Asensio'], 'medium'),
  q('Liverpool won the 2019 Champions League final against which fellow English club?', 'Tottenham Hotspur', ['Manchester City', 'Chelsea', 'Arsenal'], 'medium'),
  q('Which club won the 2020 Champions League, beating PSG 1-0 in the final?', 'Bayern Munich', ['Real Madrid', 'Liverpool', 'Manchester City'], 'medium'),
  q('Who scored the only goal for Chelsea in the 2021 Champions League final against Manchester City?', 'Kai Havertz', ['Timo Werner', 'Mason Mount', 'Christian Pulisic'], 'medium'),
  q('Manchester City won their first Champions League in 2023 as part of a treble. Who scored in the final?', 'Rodri', ['Erling Haaland', 'Kevin De Bruyne', 'Phil Foden'], 'medium'),
  q('Which club did Real Madrid beat in the 2024 Champions League final?', 'Borussia Dortmund', ['Bayern Munich', 'Manchester City', 'PSG'], 'medium'),
  q('José Mourinho won his first Champions League in 2004 with which club?', 'Porto', ['Chelsea', 'Inter Milan', 'Benfica'], 'medium'),
  q('A young Ajax side beat AC Milan to win the Champions League in which year?', '1995', ['1993', '1997', '1999'], 'hard'),
  q('Johan Cruyff’s Ajax won three straight European Cups starting in which year?', '1971', ['1969', '1974', '1976'], 'hard'),
  q('Which German club won three consecutive European Cups from 1974 to 1976?', 'Bayern Munich', ['Borussia Mönchengladbach', 'Hamburg', 'Borussia Dortmund'], 'hard'),
  q('Which is the only French club to have won the Champions League?', 'Marseille', ['PSG', 'Lyon', 'Monaco'], 'hard'),
  q('Eusébio starred as which Portuguese club won back-to-back European Cups in 1961 and 1962?', 'Benfica', ['Porto', 'Sporting CP', 'Braga'], 'hard'),
  q('The Champions League anthem is based on a piece by which composer?', 'Handel', ['Beethoven', 'Mozart', 'Bach'], 'hard'),
  q('The Europa League was previously known by what name?', 'UEFA Cup', ['Cup Winners’ Cup', 'Fairs Cup', 'Super Cup'], 'easy'),
  q('Which Spanish club has won the most Europa League / UEFA Cup titles?', 'Sevilla', ['Atlético Madrid', 'Valencia', 'Villarreal'], 'medium'),
  q('Which club won the first UEFA Conference League in 2022?', 'Roma', ['West Ham United', 'Feyenoord', 'Villarreal'], 'hard'),
  q('The 2013 all-German Champions League final at Wembley was won by which club?', 'Bayern Munich', ['Borussia Dortmund', 'Schalke 04', 'Bayer Leverkusen'], 'medium'),
  q('Who scored the late winner for Bayern in the 2013 Champions League final?', 'Arjen Robben', ['Franck Ribéry', 'Thomas Müller', 'Mario Mandžukić'], 'hard'),
  q('José Mourinho’s Inter Milan completed a treble by winning the 2010 Champions League against which club?', 'Bayern Munich', ['Barcelona', 'Chelsea', 'Manchester United'], 'medium'),
  q('Who scored both goals for Inter in the 2010 Champions League final?', 'Diego Milito', ['Samuel Eto’o', 'Wesley Sneijder', 'Goran Pandev'], 'hard'),
  q('Ronald Koeman’s free kick won Barcelona their first European Cup in which year?', '1992', ['1989', '1994', '1996'], 'hard'),
  q('Manchester United beat Chelsea on penalties in the rain in the 2008 final. In which city was it played?', 'Moscow', ['Rome', 'Athens', 'Madrid'], 'medium'),
  q('Which Chelsea captain slipped and missed a decisive penalty in the 2008 Champions League final?', 'John Terry', ['Frank Lampard', 'Ashley Cole', 'Michael Ballack'], 'medium'),
  q('AC Milan avenged their 2005 Istanbul defeat by beating Liverpool in the final of which year?', '2007', ['2006', '2008', '2009'], 'hard'),
  q('The UEFA Super Cup is contested by the winners of which two competitions?', 'Champions League and Europa League', ['Champions League and World Cup', 'Europa League and Conference League', 'Champions League and Club World Cup'], 'easy'),
  q('Which German club won the Champions League in 1997, beating Juventus in the final?', 'Borussia Dortmund', ['Bayern Munich', 'Werder Bremen', 'Hamburg'], 'hard'),
  q('Which Italian club won the 1996 Champions League on penalties against Ajax?', 'Juventus', ['AC Milan', 'Inter Milan', 'Parma'], 'hard'),
  q('Which Romanian club famously won the European Cup in 1986?', 'Steaua Bucharest', ['Dinamo Bucharest', 'Rapid Bucharest', 'CFR Cluj'], 'hard'),
  q('Red Star Belgrade won the European Cup in 1991 representing which country at the time?', 'Yugoslavia', ['Serbia', 'Croatia', 'Bulgaria'], 'hard'),
  q('How is the Champions League final decided if the score is level after extra time?', 'Penalty shootout', ['Replay', 'Away goals', 'Golden goal'], 'easy'),
  q('English clubs were banned from European competition in 1985 after a disaster at which stadium?', 'Heysel', ['Hillsborough', 'Wembley', 'Ibrox'], 'hard'),
]
