import type { BankEntry } from '../../../types/trivia'
import { q } from './entry'

/** Premier League and other domestic leagues. */
export const leagues: BankEntry[] = [
  q('In which year was the English Premier League founded?', '1992', ['1990', '1988', '1995'], 'medium'),
  q('Which club has won the most Premier League titles?', 'Manchester United', ['Manchester City', 'Liverpool', 'Chelsea'], 'easy'),
  q('Which Arsenal side went unbeaten through the entire 2003-04 Premier League season?', 'The Invincibles', ['The Untouchables', 'The Immortals', 'The Unbeatables'], 'easy'),
  q('Which club pulled off a 5000-1 shock by winning the 2015-16 Premier League?', 'Leicester City', ['West Ham United', 'Everton', 'Southampton'], 'easy'),
  q('Who is the Premier League’s all-time top scorer with 260 goals?', 'Alan Shearer', ['Wayne Rooney', 'Harry Kane', 'Thierry Henry'], 'medium'),
  q('Whose 36 goals in 2022-23 set the record for a single 38-game Premier League season?', 'Erling Haaland', ['Mohamed Salah', 'Harry Kane', 'Luis Suárez'], 'medium'),
  q('Which player holds the record for the most Premier League assists?', 'Ryan Giggs', ['Kevin De Bruyne', 'Frank Lampard', 'Cesc Fàbregas'], 'hard'),
  q('Who were the first champions of the Premier League era in 1992-93?', 'Manchester United', ['Blackburn Rovers', 'Arsenal', 'Leeds United'], 'medium'),
  q('Which club, bankrolled by Jack Walker and firing Alan Shearer, won the 1994-95 Premier League?', 'Blackburn Rovers', ['Newcastle United', 'Aston Villa', 'Nottingham Forest'], 'hard'),
  q('Manchester City’s "Centurions" hit what record Premier League points total in 2017-18?', '100', ['98', '95', '102'], 'medium'),
  q('Whose stoppage-time goal against QPR won Manchester City the 2012 Premier League title?', 'Sergio Agüero', ['Edin Džeko', 'Yaya Touré', 'David Silva'], 'medium'),
  q('How many teams are relegated from the Premier League each season?', '3', ['2', '4', '1'], 'easy'),
  q('How many points does a team earn for a win in league football?', '3', ['2', '4', '1'], 'easy'),
  q('How many clubs play in the Premier League each season?', '20', ['18', '22', '24'], 'easy'),
  q('Which club has won the most La Liga titles?', 'Real Madrid', ['Barcelona', 'Atlético Madrid', 'Athletic Bilbao'], 'medium'),
  q('What is the famous match between Real Madrid and Barcelona called?', 'El Clásico', ['El Derbi', 'La Liga Grande', 'El Superclásico'], 'easy'),
  q('Which club has won the most Serie A titles in Italy?', 'Juventus', ['AC Milan', 'Inter Milan', 'Roma'], 'easy'),
  q('Juventus won how many consecutive Serie A titles between 2012 and 2020?', '9', ['7', '8', '10'], 'hard'),
  q('Which club has dominated the Bundesliga with by far the most German titles?', 'Bayern Munich', ['Borussia Dortmund', 'Hamburg', 'Schalke 04'], 'easy'),
  q('Which club ended Bayern’s 11-year Bundesliga reign by winning the 2023-24 title unbeaten?', 'Bayer Leverkusen', ['Borussia Dortmund', 'RB Leipzig', 'Stuttgart'], 'medium'),
  q('Which club has won the most Ligue 1 titles in France?', 'PSG', ['Marseille', 'Saint-Étienne', 'Lyon'], 'medium'),
  q('Which club shocked PSG to win Ligue 1 in 2021?', 'Lille', ['Monaco', 'Lyon', 'Lens'], 'hard'),
  q('Who managed Leicester City to their miracle 2015-16 Premier League title?', 'Claudio Ranieri', ['Brendan Rodgers', 'Nigel Pearson', 'Rafael Benítez'], 'medium'),
  q('Which Leicester striker scored in a record 11 consecutive Premier League matches in 2015?', 'Jamie Vardy', ['Riyad Mahrez', 'Shinji Okazaki', 'Harry Kane'], 'hard'),
  q('The "Derby della Madonnina" is contested in which city?', 'Milan', ['Rome', 'Turin', 'Naples'], 'medium'),
  q('The "Old Firm" derby is between Rangers and which club?', 'Celtic', ['Aberdeen', 'Hearts', 'Hibernian'], 'medium'),
  q('Which club has won the most Eredivisie titles in the Netherlands?', 'Ajax', ['PSV Eindhoven', 'Feyenoord', 'AZ Alkmaar'], 'medium'),
  q('Which club has won the most league titles in Portugal?', 'Benfica', ['Porto', 'Sporting CP', 'Braga'], 'hard'),
  q('Lionel Messi joined which Major League Soccer club in 2023?', 'Inter Miami', ['LA Galaxy', 'New York City FC', 'Orlando City'], 'easy'),
  q('Cristiano Ronaldo joined which Saudi Arabian club at the start of 2023?', 'Al Nassr', ['Al Hilal', 'Al Ittihad', 'Al Ahli'], 'easy'),
  q('The North London derby is between Tottenham Hotspur and which club?', 'Arsenal', ['Chelsea', 'West Ham United', 'Fulham'], 'easy'),
  q('The Merseyside derby is contested by Liverpool and which club?', 'Everton', ['Manchester United', 'Leeds United', 'Tranmere Rovers'], 'easy'),
  q('"Der Klassiker" in Germany is Bayern Munich against which club?', 'Borussia Dortmund', ['Schalke 04', 'Hamburg', 'RB Leipzig'], 'medium'),
  q('What is the award for La Liga’s top scorer each season called?', 'Pichichi Trophy', ['Zamora Trophy', 'Di Stéfano Trophy', 'El Botín'], 'hard'),
  q('What is Serie A’s top-scorer title called in Italy?', 'Capocannoniere', ['Scudetto', 'Pallone d’Oro', 'Il Bomber'], 'hard'),
  q('Liverpool ended how many years of waiting when they won the 2019-20 Premier League?', '30', ['25', '20', '35'], 'medium'),
  q('José Mourinho won his first Premier League title with Chelsea in which season?', '2004-05', ['2005-06', '2003-04', '2006-07'], 'medium'),
  q('What nickname did José Mourinho give himself when he arrived at Chelsea in 2004?', 'The Special One', ['The Chosen One', 'The Great One', 'The Only One'], 'easy'),
  q('How many Premier League titles did Sir Alex Ferguson win before retiring in 2013?', '13', ['11', '15', '10'], 'medium'),
  q('Which manager led Arsenal for 22 years from 1996 to 2018?', 'Arsène Wenger', ['George Graham', 'Herbert Chapman', 'Unai Emery'], 'medium'),
  q('Along with Real Madrid and Barcelona, which club has never been relegated from La Liga?', 'Athletic Bilbao', ['Atlético Madrid', 'Valencia', 'Sevilla'], 'hard'),
  q('A full round of league fixtures on 26 December in England is known as what?', 'Boxing Day football', ['Christmas Cup', 'Festive Finals', 'Winter Classic'], 'medium'),
  q('Which competition do English clubs win to be promoted into the Premier League via a Wembley final?', 'The Championship play-offs', ['The FA Trophy', 'The EFL Cup', 'The Community Shield'], 'medium'),
  q('Harry Kane left Tottenham in 2023 to join which club?', 'Bayern Munich', ['Real Madrid', 'Manchester United', 'PSG'], 'medium'),
  q('What is the Italian league championship shield worn by the champions called?', 'Scudetto', ['Tricolore', 'Corona', 'Stella'], 'medium'),
  q('Napoli’s 2022-23 Serie A title was their first since the era of which player?', 'Diego Maradona', ['Careca', 'Gianfranco Zola', 'Edinson Cavani'], 'medium'),
  q('The Manchester derby is Manchester United against which club?', 'Manchester City', ['Liverpool', 'Leeds United', 'Bolton Wanderers'], 'easy'),
  q('Which trophy do the Premier League champions and FA Cup winners contest each August?', 'The Community Shield', ['The Charity Bowl', 'The Super Trophy', 'The League Shield'], 'medium'),
  q('Which two Sheffield clubs contest the Steel City derby?', 'United and Wednesday', ['City and Rovers', 'Athletic and Town', 'United and City'], 'hard'),
  q('Which Spanish club plays its home games at the Mestalla?', 'Valencia', ['Sevilla', 'Real Betis', 'Villarreal'], 'hard'),
]
