import type { BankEntry } from '../../../types/trivia'
import { q } from './entry'

/** National teams, nicknames and international tournaments. */
export const nationalTeams: BankEntry[] = [
  q('Which national team is known as the "Seleção" and plays in famous yellow shirts?', 'Brazil', ['Portugal', 'Colombia', 'Spain'], 'easy'),
  q('Which national team is known as the "Azzurri"?', 'Italy', ['France', 'Argentina', 'Uruguay'], 'easy'),
  q('Which national team is known as "Les Bleus"?', 'France', ['Belgium', 'Netherlands', 'Italy'], 'easy'),
  q('Which national team is known as "La Albiceleste"?', 'Argentina', ['Uruguay', 'Chile', 'Mexico'], 'medium'),
  q('Which national team plays in orange and is nicknamed "Oranje"?', 'Netherlands', ['Belgium', 'Denmark', 'Sweden'], 'easy'),
  q('Which national team is known as "La Roja"?', 'Spain', ['Portugal', 'Chile', 'Mexico'], 'easy'),
  q('The England national team is known by which nickname?', 'The Three Lions', ['The Bulldogs', 'The Red Roses', 'The Crusaders'], 'easy'),
  q('Which national team is known as "La Celeste"?', 'Uruguay', ['Argentina', 'Honduras', 'Ecuador'], 'hard'),
  q('The Mexico national team is commonly known as what?', 'El Tri', ['Los Aztecas', 'La Verde', 'Los Charros'], 'medium'),
  q('Which national team is nicknamed the "Samurai Blue"?', 'Japan', ['South Korea', 'China', 'Thailand'], 'medium'),
  q('The Australia national team is known by which nickname?', 'The Socceroos', ['The Kangaroos', 'The Wallabies', 'The Matildas'], 'easy'),
  q('Which African national team is known as the "Super Eagles"?', 'Nigeria', ['Ghana', 'Cameroon', 'Senegal'], 'medium'),
  q('Which African national team is known as the "Indomitable Lions"?', 'Cameroon', ['Ivory Coast', 'Morocco', 'Algeria'], 'medium'),
  q('Which African national team is known as "The Elephants"?', 'Ivory Coast', ['Kenya', 'South Africa', 'Mali'], 'medium'),
  q('Which African national team is known as the "Lions of Teranga"?', 'Senegal', ['Tunisia', 'Guinea', 'DR Congo'], 'hard'),
  q('Which African national team is known as the "Black Stars"?', 'Ghana', ['Nigeria', 'Zambia', 'Angola'], 'medium'),
  q('Which country, nicknamed "The Pharaohs", has won the most Africa Cup of Nations titles?', 'Egypt', ['Cameroon', 'Ghana', 'Nigeria'], 'medium'),
  q('What does AFCON stand for?', 'Africa Cup of Nations', ['African Football Confederation', 'Africa Champions of Nations', 'African Federation Cup'], 'easy'),
  q('Which is the oldest international continental football tournament, first held in 1916?', 'Copa América', ['The European Championship', 'AFCON', 'The Gold Cup'], 'medium'),
  q('Which country has won the most Copa América titles?', 'Argentina', ['Brazil', 'Uruguay', 'Chile'], 'hard'),
  q('Which country has won the most European Championships, with four titles?', 'Spain', ['Germany', 'France', 'Italy'], 'medium'),
  q('Which country won Euro 2024 in Germany?', 'Spain', ['England', 'France', 'Italy'], 'easy'),
  q('Which country won Euro 2020, played in 2021, beating England at Wembley?', 'Italy', ['France', 'Spain', 'Portugal'], 'medium'),
  q('Portugal won their first major trophy at Euro 2016 by beating which host nation in the final?', 'France', ['Germany', 'Spain', 'Wales'], 'medium'),
  q('Which unfancied nation shocked Europe by winning Euro 2004?', 'Greece', ['Denmark', 'Czech Republic', 'Portugal'], 'medium'),
  q('Which country won Euro 1992 after being invited late when Yugoslavia was excluded?', 'Denmark', ['Sweden', 'Norway', 'Ireland'], 'hard'),
  q('Between 2008 and 2012, Spain won three consecutive major tournaments: two Euros and what else?', 'The World Cup', ['The Confederations Cup', 'The Nations League', 'The Olympics'], 'medium'),
  q('The "Panenka" penalty is named after a player who chipped the keeper in the final of which tournament?', 'Euro 1976', ['World Cup 1974', 'Euro 1980', 'World Cup 1982'], 'hard'),
  q('England lost the finals of Euro 2020 and Euro 2024. Which manager led them in both?', 'Gareth Southgate', ['Roy Hodgson', 'Sam Allardyce', 'Fabio Capello'], 'medium'),
  q('Which country has won the most Women’s World Cups?', 'United States', ['Germany', 'Norway', 'Japan'], 'medium'),
  q('Which country won the 2023 Women’s World Cup?', 'Spain', ['England', 'United States', 'Australia'], 'medium'),
  q('Messi won his first major international trophy at the 2021 Copa América, beating which host in the final?', 'Brazil', ['Uruguay', 'Chile', 'Colombia'], 'medium'),
  q('Which country won the first UEFA Nations League in 2019?', 'Portugal', ['France', 'Spain', 'Netherlands'], 'hard'),
  q('Neymar’s decisive penalty won Brazil their first Olympic football gold at which Games?', 'Rio 2016', ['London 2012', 'Beijing 2008', 'Tokyo 2020'], 'hard'),
  q('In which year was FIFA founded?', '1904', ['1930', '1888', '1912'], 'hard'),
  q('Which confederation governs football in South America?', 'CONMEBOL', ['CONCACAF', 'UEFA', 'CAF'], 'medium'),
  q('CONCACAF governs football in which region?', 'North and Central America and the Caribbean', ['South America', 'Africa', 'Asia and Oceania'], 'hard'),
  q('Who holds the record for the most men’s international appearances?', 'Cristiano Ronaldo', ['Lionel Messi', 'Sergio Ramos', 'Gianluigi Buffon'], 'medium'),
  q('Whose record for most men’s international goals did Cristiano Ronaldo break?', 'Ali Daei', ['Pelé', 'Ferenc Puskás', 'Miroslav Klose'], 'hard'),
  q('Which tiny nation reached the Euro 2016 quarter-finals and popularised the "thunderclap" celebration?', 'Iceland', ['Wales', 'Albania', 'Northern Ireland'], 'medium'),
  q('Which country’s national kit features a distinctive red-and-white checkerboard pattern?', 'Croatia', ['Poland', 'Austria', 'Serbia'], 'easy'),
  q('Gareth Bale led which country to a surprise Euro 2016 semi-final?', 'Wales', ['Scotland', 'Northern Ireland', 'Ireland'], 'medium'),
  q('The first-ever official international match in 1872 was between England and which country?', 'Scotland', ['Wales', 'France', 'Germany'], 'hard'),
  q('Which "golden generation" topped the FIFA rankings for years without winning a major trophy?', 'Belgium', ['Portugal', 'Colombia', 'Chile'], 'medium'),
  q('Which country does the German national team’s nickname "Die Mannschaft" simply mean?', 'The Team', ['The Machine', 'The Eagles', 'The Power'], 'medium'),
  q('Which South American country is nicknamed "La Vinotinto" for its wine-coloured shirts?', 'Venezuela', ['Bolivia', 'Peru', 'Paraguay'], 'hard'),
  q('The United States men’s team plays its fiercest rivalry, dubbed "Dos a Cero", against which country?', 'Mexico', ['Canada', 'Costa Rica', 'Honduras'], 'hard'),
  q('Which country hosts the Maracanã and has produced Pelé, Ronaldo and Neymar?', 'Brazil', ['Argentina', 'Portugal', 'Uruguay'], 'easy'),
  q('Zinedine Zidane’s family roots, celebrated during France’s 1998 win, trace to which country?', 'Algeria', ['Morocco', 'Tunisia', 'Senegal'], 'hard'),
  q('Which country won the first-ever European Championship in 1960?', 'Soviet Union', ['Spain', 'Yugoslavia', 'France'], 'hard'),
]
