import type { BankEntry } from '../../../types/trivia'
import { q } from './entry'

/** Legendary and famous players, past and present. */
export const players: BankEntry[] = [
  q('How many Ballon d’Or awards has Lionel Messi won?', '8', ['7', '6', '9'], 'easy'),
  q('Which country does Lionel Messi play for?', 'Argentina', ['Spain', 'Brazil', 'Uruguay'], 'easy'),
  q('How many Ballon d’Or awards has Cristiano Ronaldo won?', '5', ['4', '6', '7'], 'medium'),
  q('Cristiano Ronaldo is famously known by which nickname combining his initials and shirt number?', 'CR7', ['CR9', 'RC7', 'CR10'], 'easy'),
  q('How many World Cups did Pelé win, more than any other player?', '3', ['2', '4', '1'], 'easy'),
  q('Which country did Diego Maradona play for?', 'Argentina', ['Brazil', 'Uruguay', 'Chile'], 'easy'),
  q('The "Cruyff turn" is named after a legendary player from which country?', 'Netherlands', ['Germany', 'Denmark', 'Belgium'], 'medium'),
  q('The Dutch playing style of the 1970s, where players fluidly swap positions, is called what?', 'Total Football', ['Complete Football', 'Free Football', 'Dream Football'], 'medium'),
  q('German legend Franz Beckenbauer was known by which nickname?', 'Der Kaiser', ['Der Bomber', 'Der König', 'Der Panzer'], 'medium'),
  q('Which Northern Irish winger was told "Maradona good, Pelé better, George ___"?', 'Best', ['Moore', 'Law', 'Charlton'], 'hard'),
  q('Benfica legend Eusébio was known by which nickname?', 'The Black Panther', ['The Black Pearl', 'The Lion', 'The Jaguar'], 'hard'),
  q('FIFA’s award for the most beautiful goal of the year is named after which Hungarian legend?', 'Ferenc Puskás', ['Sándor Kocsis', 'Zoltán Czibor', 'Gyula Grosics'], 'medium'),
  q('Which Argentine-born forward starred in Real Madrid’s five straight European Cup wins in the 1950s?', 'Alfredo Di Stéfano', ['Ferenc Puskás', 'Raymond Kopa', 'Paco Gento'], 'hard'),
  q('Which smiling Brazilian magician won the 2005 Ballon d’Or while at Barcelona?', 'Ronaldinho', ['Kaká', 'Rivaldo', 'Robinho'], 'medium'),
  q('Brazilian striker Ronaldo was known in Spain by which nickname?', 'El Fenómeno', ['El Matador', 'El Rey', 'O Rei'], 'medium'),
  q('Which country does Zlatan Ibrahimović play for?', 'Sweden', ['Norway', 'Denmark', 'Croatia'], 'easy'),
  q('Which Italian goalkeeper played over 1,100 career games across four decades?', 'Gianluigi Buffon', ['Dino Zoff', 'Francesco Toldo', 'Salvatore Sirigu'], 'medium'),
  q('Which Spanish goalkeeper, nicknamed "San Iker", captained Spain to the 2010 World Cup?', 'Iker Casillas', ['Víctor Valdés', 'Pepe Reina', 'David de Gea'], 'medium'),
  q('Manuel Neuer redefined goalkeeping with which style of play?', 'Sweeper-keeper', ['Shot-stopper', 'Line-keeper', 'Libero-keeper'], 'medium'),
  q('Who is the only goalkeeper ever to win the Ballon d’Or?', 'Lev Yashin', ['Gianluigi Buffon', 'Dino Zoff', 'Peter Schmeichel'], 'medium'),
  q('Soviet goalkeeper Lev Yashin was known by which nickname for his all-black kit?', 'The Black Spider', ['The Black Cat', 'The Black Eagle', 'The Black Wall'], 'hard'),
  q('Xavi and Andrés Iniesta ran the midfield of which possession style perfected at Barcelona?', 'Tiki-taka', ['Catenaccio', 'Gegenpressing', 'Joga bonito'], 'medium'),
  q('Which bearded Italian was the archetypal deep-lying playmaker for Milan and Juventus?', 'Andrea Pirlo', ['Gennaro Gattuso', 'Daniele De Rossi', 'Marco Verratti'], 'medium'),
  q('Which Englishman was famous for his free kicks and crosses and wore number 7 for Manchester United?', 'David Beckham', ['Paul Scholes', 'Steven Gerrard', 'Frank Lampard'], 'easy'),
  q('Who is Manchester United’s all-time top goalscorer?', 'Wayne Rooney', ['Bobby Charlton', 'Ryan Giggs', 'Eric Cantona'], 'medium'),
  q('Who became England’s all-time top scorer in 2023?', 'Harry Kane', ['Wayne Rooney', 'Gary Lineker', 'Bobby Charlton'], 'medium'),
  q('Mohamed Salah, the "Egyptian King", plays for which Premier League club?', 'Liverpool', ['Chelsea', 'Arsenal', 'Manchester City'], 'easy'),
  q('Sadio Mané won the 2021 Africa Cup of Nations with which country?', 'Senegal', ['Ivory Coast', 'Mali', 'Guinea'], 'medium'),
  q('Chelsea legend Didier Drogba played international football for which country?', 'Ivory Coast', ['Ghana', 'Cameroon', 'Senegal'], 'medium'),
  q('Which Cameroonian striker won back-to-back Champions Leagues with Barcelona and Inter in 2009 and 2010?', 'Samuel Eto’o', ['Didier Drogba', 'Emmanuel Adebayor', 'Michael Essien'], 'medium'),
  q('Which is the only African player to win the Ballon d’Or, later becoming president of Liberia?', 'George Weah', ['Samuel Eto’o', 'Didier Drogba', 'Abedi Pelé'], 'hard'),
  q('Which Croatian midfielder broke the Messi-Ronaldo duopoly by winning the 2018 Ballon d’Or?', 'Luka Modrić', ['Ivan Rakitić', 'Mario Mandžukić', 'Mateo Kovačić'], 'medium'),
  q('Which Brazilian was the last player before Messi and Ronaldo’s reign to win the Ballon d’Or, in 2007?', 'Kaká', ['Ronaldinho', 'Rivaldo', 'Adriano'], 'medium'),
  q('Which French striker won the 2022 Ballon d’Or after a stellar Real Madrid season?', 'Karim Benzema', ['Kylian Mbappé', 'Antoine Griezmann', 'Olivier Giroud'], 'medium'),
  q('Which Manchester City midfielder won the 2024 Ballon d’Or?', 'Rodri', ['Erling Haaland', 'Kevin De Bruyne', 'Jude Bellingham'], 'medium'),
  q('Erling Haaland plays international football for which country?', 'Norway', ['Sweden', 'Denmark', 'Germany'], 'easy'),
  q('Kylian Mbappé became the second teenager after Pelé to score in a World Cup final. In which year?', '2018', ['2014', '2022', '2010'], 'easy'),
  q('Who is Brazil’s all-time top goalscorer, having overtaken Pelé in 2023?', 'Neymar', ['Ronaldo', 'Romário', 'Rivaldo'], 'medium'),
  q('Which Polish striker once scored 5 goals in 9 minutes as a substitute for Bayern Munich?', 'Robert Lewandowski', ['Arkadiusz Milik', 'Miroslav Klose', 'Lukas Podolski'], 'medium'),
  q('Luis Suárez is the all-time top scorer for which national team?', 'Uruguay', ['Chile', 'Colombia', 'Paraguay'], 'medium'),
  q('Which Italian defender won the 2006 Ballon d’Or after captaining Italy to the World Cup?', 'Fabio Cannavaro', ['Gianluigi Buffon', 'Alessandro Nesta', 'Marco Materazzi'], 'hard'),
  q('Which German holds his country’s record of 150 international caps?', 'Lothar Matthäus', ['Miroslav Klose', 'Bastian Schweinsteiger', 'Philipp Lahm'], 'hard'),
  q('Which one-club legend spent 25 seasons at AC Milan, mostly as captain?', 'Paolo Maldini', ['Franco Baresi', 'Alessandro Costacurta', 'Andrea Pirlo'], 'medium'),
  q('Which Roman idol spent his entire 25-year career at Roma?', 'Francesco Totti', ['Daniele De Rossi', 'Alessandro Del Piero', 'Antonio Cassano'], 'medium'),
  q('Which Liverpool captain lifted the Champions League after the Istanbul comeback in 2005?', 'Steven Gerrard', ['Jamie Carragher', 'Sami Hyypiä', 'Michael Owen'], 'medium'),
  q('Which midfielder is Chelsea’s all-time top goalscorer?', 'Frank Lampard', ['Didier Drogba', 'Eden Hazard', 'Gianfranco Zola'], 'medium'),
  q('Who is Arsenal’s all-time top goalscorer?', 'Thierry Henry', ['Ian Wright', 'Dennis Bergkamp', 'Robin van Persie'], 'medium'),
  q('Who is Manchester City’s all-time top goalscorer?', 'Sergio Agüero', ['Erling Haaland', 'Raheem Sterling', 'Carlos Tevez'], 'hard'),
  q('Lionel Messi came through which famous Barcelona youth academy?', 'La Masia', ['La Fábrica', 'La Cantera', 'La Escuela'], 'medium'),
  q('Cristiano Ronaldo began his professional career at which Portuguese club?', 'Sporting CP', ['Benfica', 'Porto', 'Braga'], 'medium'),
  q('Which Brazilian winger, a two-time World Cup winner nicknamed "Little Bird", is celebrated for his dribbling?', 'Garrincha', ['Jairzinho', 'Zico', 'Rivelino'], 'hard'),
  q('Which magazine originally created and awarded the Ballon d’Or?', 'France Football', ['L’Équipe', 'Marca', 'Kicker'], 'hard'),
]
