import type { BankEntry } from '../../../types/trivia'
import { q } from './entry'

/** Records, transfers and historic moments. */
export const records: BankEntry[] = [
  q('Whose move to PSG in 2017 remains the most expensive transfer in history?', 'Neymar', ['Kylian Mbappé', 'Philippe Coutinho', 'Ousmane Dembélé'], 'easy'),
  q('Roughly how much did PSG pay Barcelona for Neymar in 2017?', '€222 million', ['€150 million', '€180 million', '€250 million'], 'medium'),
  q('Which Welshman’s 2013 move to Real Madrid broke the world transfer record?', 'Gareth Bale', ['Ryan Giggs', 'Aaron Ramsey', 'Ian Rush'], 'medium'),
  q('Which player’s 2001 move to Real Madrid from Juventus set a world record that stood for years?', 'Zinedine Zidane', ['Luís Figo', 'Ronaldo', 'David Beckham'], 'hard'),
  q('Who scored the fastest goal in World Cup history, after around 11 seconds in 2002?', 'Hakan Şükür', ['Ronaldo', 'Michael Owen', 'Raúl'], 'hard'),
  q('Which Senegalese striker scored the fastest Premier League hat-trick, in under 3 minutes?', 'Sadio Mané', ['El Hadji Diouf', 'Demba Ba', 'Papiss Cissé'], 'hard'),
  q('The record international win is 31-0, achieved by Australia against which side in 2001?', 'American Samoa', ['Tonga', 'Fiji', 'Vanuatu'], 'hard'),
  q('Lionel Messi holds the record for most goals in a calendar year. How many did he score in 2012?', '91', ['85', '75', '100'], 'medium'),
  q('Whose 40-goal Bundesliga season record did Robert Lewandowski break in 2021?', 'Gerd Müller', ['Karl-Heinz Rummenigge', 'Jupp Heynckes', 'Uwe Seeler'], 'hard'),
  q('German striker Gerd Müller was known by which nickname?', 'Der Bomber', ['Der Kaiser', 'Der Hammer', 'Der Blitz'], 'medium'),
  q('The record football attendance of around 200,000 was set at the 1950 World Cup in which stadium?', 'The Maracanã', ['Wembley', 'Estadio Azteca', 'Camp Nou'], 'medium'),
  q('Who was the first player to reach 100 Champions League goals?', 'Cristiano Ronaldo', ['Lionel Messi', 'Raúl', 'Robert Lewandowski'], 'hard'),
  q('Which player scored an incredible 672 goals for a single club, Barcelona?', 'Lionel Messi', ['Xavi', 'Luis Suárez', 'César Rodríguez'], 'medium'),
  q('The first World Cup to use VAR was held in which year?', '2018', ['2014', '2022', '2010'], 'medium'),
  q('Which goalkeeper became the oldest World Cup player ever at 45 in 2018?', 'Essam El-Hadary', ['Gianluigi Buffon', 'Tim Howard', 'Keylor Navas'], 'hard'),
  q('Which 17-year-old became the youngest ever World Cup player in 1982?', 'Norman Whiteside', ['Pelé', 'Michael Owen', 'Kylian Mbappé'], 'hard'),
  q('The first Ballon d’Or in 1956 was won by which English winger?', 'Stanley Matthews', ['Bobby Charlton', 'Tom Finney', 'Nat Lofthouse'], 'hard'),
  q('The first World Cup mascot, "World Cup Willie", appeared at which tournament?', '1966 in England', ['1970 in Mexico', '1962 in Chile', '1974 in West Germany'], 'hard'),
  q('Which English club, founded in 1857, is recognised as the world’s oldest?', 'Sheffield FC', ['Notts County', 'Aston Villa', 'Stoke City'], 'hard'),
  q('Which is the oldest national football competition in the world, first held in 1871?', 'The FA Cup', ['The Copa del Rey', 'The Coppa Italia', 'The Scottish Cup'], 'medium'),
  q('Arsenal’s Invincibles eventually stretched their unbeaten league run to how many games?', '49', ['45', '50', '55'], 'medium'),
  q('The legendary 1960 European Cup final, won 7-3 by Real Madrid over Eintracht Frankfurt, was played where?', 'Hampden Park, Glasgow', ['Wembley, London', 'Heysel, Brussels', 'Parc des Princes, Paris'], 'hard'),
  q('The first golden goal in World Cup history was scored by which French defender in 1998?', 'Laurent Blanc', ['Lilian Thuram', 'Marcel Desailly', 'Bixente Lizarazu'], 'hard'),
  q('Which Manchester United player launched a kung-fu kick at a fan at Selhurst Park in 1995?', 'Eric Cantona', ['Roy Keane', 'Paul Ince', 'Mark Hughes'], 'medium'),
  q('Diego Maradona inspired which Italian club to its first two league titles in the late 1980s?', 'Napoli', ['Roma', 'Sampdoria', 'Fiorentina'], 'medium'),
  q('Who scored the first-ever World Cup hat-trick, for the USA in 1930?', 'Bert Patenaude', ['Bart McGhee', 'Archie Stark', 'Billy Gonsalves'], 'hard'),
  q('Which player has scored the most Premier League hat-tricks, with 12?', 'Sergio Agüero', ['Alan Shearer', 'Harry Kane', 'Thierry Henry'], 'hard'),
  q('In 1979, Trevor Francis became Britain’s first player transferred for what fee?', '£1 million', ['£500,000', '£2 million', '£750,000'], 'hard'),
  q('Who is the all-time top scorer in Women’s World Cup history with 17 goals?', 'Marta', ['Abby Wambach', 'Birgit Prinz', 'Alex Morgan'], 'medium'),
  q('The first Women’s Ballon d’Or in 2018 was won by which Norwegian striker?', 'Ada Hegerberg', ['Marta', 'Megan Rapinoe', 'Alexia Putellas'], 'hard'),
  q('Which Spanish midfielder won back-to-back Women’s Ballon d’Or awards in 2023 and 2024?', 'Aitana Bonmatí', ['Alexia Putellas', 'Jenni Hermoso', 'Olga Carmona'], 'medium'),
  q('The 1994 World Cup final was the first to finish 0-0 and be decided how?', 'By penalty shootout', ['By golden goal', 'By replay', 'By extra time'], 'medium'),
  q('Which club did a 17-year-old Kylian Mbappé help to a shock Ligue 1 title in 2017?', 'Monaco', ['PSG', 'Lyon', 'Nice'], 'medium'),
  q('Jude Bellingham left Borussia Dortmund in 2023 to join which club?', 'Real Madrid', ['Manchester City', 'Liverpool', 'Bayern Munich'], 'medium'),
  q('Which Italian goalkeeper captained his country to the 2006 World Cup and kept a record 5 clean sheets?', 'Gianluigi Buffon', ['Francesco Toldo', 'Angelo Peruzzi', 'Marco Amelia'], 'hard'),
  q('Manchester United’s 1968 European Cup win came ten years after which tragedy?', 'The Munich air disaster', ['The Superga air disaster', 'The Ibrox disaster', 'The Bradford fire'], 'medium'),
  q('Which Brazilian women’s legend was named FIFA World Player of the Year five years in a row from 2006 to 2010?', 'Marta', ['Formiga', 'Cristiane', 'Sissi'], 'hard'),
  q('Pelé scored his 1,000th career goal playing for which club?', 'Santos', ['New York Cosmos', 'Flamengo', 'Corinthians'], 'hard'),
  q('Which Mexican goalkeeper was the first player to appear in five World Cups, from 1950 to 1966?', 'Antonio Carbajal', ['Gilmar', 'Lev Yashin', 'Antonio Roma'], 'hard'),
  q('The fastest hat-trick in World Cup history took under 4 minutes in 1982. Which Hungarian scored it?', 'László Kiss', ['Tibor Nyilasi', 'Ferenc Puskás', 'Flórián Albert'], 'hard'),
  q('Which country hosted the first World Cup that expanded to 32 teams, in 1998?', 'France', ['USA', 'Japan', 'Germany'], 'medium'),
  q('Which club won the first FIFA Club World Championship in 2000?', 'Corinthians', ['Real Madrid', 'Manchester United', 'Vasco da Gama'], 'hard'),
  q('Which stadium hosted the famous "Game of the Century", Italy 4-3 West Germany, in 1970?', 'Estadio Azteca', ['The Maracanã', 'Estadio Centenario', 'Wembley'], 'hard'),
  q('Which player won World Cups 12 years apart, in 1958 and 1970?', 'Pelé', ['Garrincha', 'Jairzinho', 'Carlos Alberto'], 'medium'),
  q('Which iconic photo moment saw Pelé and which England defender swap shirts at the 1970 World Cup?', 'Bobby Moore', ['Bobby Charlton', 'Gordon Banks', 'Geoff Hurst'], 'hard'),
  q('Gordon Banks made the "save of the century" at the 1970 World Cup from whose header?', 'Pelé', ['Jairzinho', 'Tostão', 'Rivelino'], 'medium'),
  q('Which goalkeeper scored over 100 career goals from free kicks and penalties for São Paulo?', 'Rogério Ceni', ['José Luis Chilavert', 'René Higuita', 'Jorge Campos'], 'hard'),
  q('Colombian keeper René Higuita is famous for inventing which outrageous clearance?', 'The scorpion kick', ['The dragon flick', 'The backheel volley', 'The flying wall'], 'medium'),
  q('Who captained Germany to the 2014 World Cup title before retiring from international football?', 'Philipp Lahm', ['Bastian Schweinsteiger', 'Manuel Neuer', 'Per Mertesacker'], 'hard'),
  q('Which striker scored the fastest Premier League goal ever, after just 7.69 seconds in 2019?', 'Shane Long', ['Jamie Vardy', 'Sadio Mané', 'Dwight Gayle'], 'hard'),
]
