import type { BankEntry } from '../../../types/trivia'
import { q } from './entry'

/** Laws of the game, positions, tactics and football terms. */
export const rules: BankEntry[] = [
  q('How many players does each team have on the pitch at kick-off?', '11', ['10', '12', '9'], 'easy'),
  q('How long is a standard football match, excluding stoppage time?', '90 minutes', ['80 minutes', '100 minutes', '120 minutes'], 'easy'),
  q('How long is the half-time interval in a standard match?', '15 minutes', ['10 minutes', '20 minutes', '5 minutes'], 'easy'),
  q('How long does extra time last in total?', '30 minutes', ['20 minutes', '15 minutes', '45 minutes'], 'easy'),
  q('What happens when a player receives two yellow cards in the same match?', 'They are sent off', ['They are substituted', 'They miss the next match only', 'They concede a penalty'], 'easy'),
  q('Can a team replace a player who has been sent off?', 'No, they play with 10', ['Yes, after 10 minutes', 'Yes, with a substitute', 'Only in extra time'], 'easy'),
  q('How far is the penalty spot from the goal line?', '12 yards', ['10 yards', '14 yards', '16 yards'], 'medium'),
  q('How tall is a full-size football goal?', '8 feet', ['7 feet', '9 feet', '10 feet'], 'hard'),
  q('From which restart can a player NOT be offside?', 'A throw-in', ['A free kick', 'Open play', 'A pass from the keeper'], 'medium'),
  q('What does VAR stand for?', 'Video Assistant Referee', ['Video Analysis Review', 'Virtual Assistant Referee', 'Video Assisted Replay'], 'easy'),
  q('Which player is the only one allowed to handle the ball, and only inside their own penalty area?', 'The goalkeeper', ['The captain', 'The sweeper', 'The last defender'], 'easy'),
  q('What is awarded if the goalkeeper picks up a deliberate back-pass from a teammate’s foot?', 'An indirect free kick', ['A penalty', 'A corner', 'A drop ball'], 'medium'),
  q('What is awarded when a defending player is the last to touch the ball before it crosses their own goal line?', 'A corner kick', ['A goal kick', 'A throw-in', 'A drop ball'], 'easy'),
  q('For a legal throw-in, the ball must be delivered from behind and over the head with how many hands?', 'Both hands', ['One hand', 'Either hand', 'No specific rule'], 'medium'),
  q('From which type of free kick can you score directly without another player touching the ball?', 'A direct free kick', ['An indirect free kick', 'Neither type', 'Only a penalty'], 'medium'),
  q('How many kicks does each team take in a standard penalty shootout before sudden death?', '5', ['3', '7', '10'], 'easy'),
  q('What happens if a penalty shootout is level after five kicks each?', 'Sudden death, one kick each', ['A replay', 'A coin toss', 'Five more kicks each'], 'medium'),
  q('How many substitutions are teams allowed in most competitions today?', '5', ['3', '2', 'Unlimited'], 'medium'),
  q('What is the official on the touchline who signals offsides called?', 'Assistant referee', ['Fourth official', 'Line judge', 'Touch referee'], 'medium'),
  q('When a referee lets play continue after a foul because it benefits the fouled team, this is called what?', 'Advantage', ['Play-on privilege', 'Continuation', 'Waiver'], 'medium'),
  q('What is the radius of the centre circle?', '10 yards', ['8 yards', '12 yards', '15 yards'], 'hard'),
  q('The penalty area is commonly known by what nickname based on its depth in yards?', 'The 18-yard box', ['The 16-yard box', 'The 20-yard box', 'The 12-yard box'], 'medium'),
  q('What is the smaller box inside the penalty area officially called?', 'The goal area', ['The keeper’s box', 'The safety zone', 'The inner area'], 'medium'),
  q('Can a goal be scored directly from a corner kick?', 'Yes', ['No', 'Only if it deflects', 'Only in extra time'], 'medium'),
  q('A goal scored directly from a corner kick is known as what?', 'An Olympic goal', ['A corner special', 'A banana goal', 'A phantom goal'], 'hard'),
  q('Can a goal be scored directly from a throw-in?', 'No', ['Yes', 'Only against the keeper', 'Only in the six-yard box'], 'medium'),
  q('In football notation, which position does the abbreviation "GK" refer to?', 'Goalkeeper', ['Goal kicker', 'General kicker', 'Game captain'], 'easy'),
  q('Which shirt number is traditionally associated with the creative playmaker?', '10', ['7', '9', '8'], 'medium'),
  q('Which shirt number is traditionally worn by the main striker?', '9', ['11', '6', '4'], 'easy'),
  q('A striker who drops deep into midfield instead of staying high is called what?', 'A false nine', ['A shadow striker', 'A hidden ten', 'A deep nine'], 'medium'),
  q('The defensive position playing behind the main defensive line, popular in Italy, is called what?', 'Libero', ['Trequartista', 'Regista', 'Mezzala'], 'hard'),
  q('In a 4-4-2 formation, what does the first number represent?', 'Defenders', ['Forwards', 'Midfielders', 'Substitutes'], 'easy'),
  q('The highly defensive Italian tactical system of the 1960s is known as what?', 'Catenaccio', ['Tiki-taka', 'Totaalvoetbal', 'Zona mista'], 'hard'),
  q('The high-intensity pressing style associated with Jürgen Klopp is called what?', 'Gegenpressing', ['Tiki-taka', 'Catenaccio', 'Park the bus'], 'medium'),
  q('What is it called when a player scores three goals in one match?', 'A hat-trick', ['A triple', 'A treble', 'A trio'], 'easy'),
  q('What does a goalkeeper "keep" when their team concedes no goals in a match?', 'A clean sheet', ['A shutout sheet', 'A white wall', 'A zero card'], 'easy'),
  q('What is it called when a player scores two goals in one match?', 'A brace', ['A pair', 'A double-up', 'A duet'], 'easy'),
  q('Playing the ball through an opponent’s legs is known as what?', 'A nutmeg', ['A tunnel pass', 'A slip', 'A needle'], 'easy'),
  q('Striking the ball with your kicking leg wrapped behind your standing leg is called what?', 'A rabona', ['A panenka', 'An elastico', 'A trivela'], 'medium'),
  q('A softly chipped penalty down the middle of the goal is named after which player?', 'Antonín Panenka', ['Pelé', 'Michel Platini', 'Zico'], 'medium'),
  q('When a team defends with everyone behind the ball, it is said to be doing what?', 'Parking the bus', ['Closing the gate', 'Building the wall', 'Dropping anchor'], 'medium'),
  q('Is an attacker who is exactly level with the second-last defender offside?', 'No, level is onside', ['Yes, always', 'Only inside the box', 'Only from a free kick'], 'medium'),
  q('Which long-standing tie-breaker rule did UEFA abolish in its competitions in 2021?', 'The away goals rule', ['The golden goal', 'The silver goal', 'Extra time'], 'hard'),
  q('For a goal to count, how much of the ball must cross the goal line?', 'The whole ball', ['Half the ball', 'Any part of the ball', 'Most of the ball'], 'medium'),
  q('Which body is responsible for the Laws of the Game?', 'IFAB', ['FIFA', 'UEFA', 'The FA'], 'hard'),
  q('How many Laws of the Game are there?', '17', ['15', '20', '12'], 'hard'),
  q('Kicking the ball while falling backwards over your own head is called what?', 'A bicycle kick', ['A scorpion kick', 'A scissor volley', 'A flip shot'], 'easy'),
  q('What colour card signals a caution?', 'Yellow', ['Red', 'Blue', 'Green'], 'easy'),
  q('If the referee awards an indirect free kick, what must happen before a goal can be scored?', 'Another player must touch the ball', ['The keeper must touch it', 'It must be passed backwards', 'The wall must retreat 10 yards'], 'medium'),
  q('The curved D-shape on the edge of the penalty area exists to keep players how far from the penalty spot?', '10 yards', ['12 yards', '8 yards', '6 yards'], 'hard'),
]
