import type { BankEntry } from '../../../types/trivia'
import { q } from './entry'

/** FIFA World Cup — tournaments, finals, hosts, moments. */
export const worldCup: BankEntry[] = [
  q('Which country hosted and won the first FIFA World Cup in 1930?', 'Uruguay', ['Brazil', 'Italy', 'Argentina'], 'medium'),
  q('Which country has won the most FIFA World Cups?', 'Brazil', ['Germany', 'Italy', 'Argentina'], 'easy'),
  q('How many World Cups has Brazil won?', '5', ['4', '3', '6'], 'easy'),
  q('Which country won the 2022 FIFA World Cup?', 'Argentina', ['France', 'Brazil', 'Croatia'], 'easy'),
  q('Which country hosted the 2022 FIFA World Cup?', 'Qatar', ['Russia', 'United Arab Emirates', 'Saudi Arabia'], 'easy'),
  q('Who scored a hat-trick in the 2022 World Cup final but still finished on the losing side?', 'Kylian Mbappé', ['Lionel Messi', 'Olivier Giroud', 'Julián Álvarez'], 'medium'),
  q('Which country won the 2018 FIFA World Cup?', 'France', ['Croatia', 'Brazil', 'Germany'], 'easy'),
  q('Which country lost the 2018 World Cup final to France?', 'Croatia', ['Belgium', 'England', 'Brazil'], 'medium'),
  q('Which country won the 2014 FIFA World Cup?', 'Germany', ['Argentina', 'Brazil', 'Netherlands'], 'easy'),
  q('Who scored the winning goal in the 2014 World Cup final?', 'Mario Götze', ['Thomas Müller', 'Miroslav Klose', 'André Schürrle'], 'medium'),
  q('What was the score when Germany beat Brazil in the 2014 World Cup semi-final?', '7-1', ['5-0', '6-2', '4-1'], 'easy'),
  q('Which country won the 2010 FIFA World Cup?', 'Spain', ['Netherlands', 'Germany', 'Brazil'], 'easy'),
  q('Who scored the winning goal for Spain in the 2010 World Cup final?', 'Andrés Iniesta', ['David Villa', 'Xavi', 'Fernando Torres'], 'medium'),
  q('The 2010 World Cup was the first held on which continent?', 'Africa', ['Asia', 'North America', 'Oceania'], 'easy'),
  q('Which country won the 2006 FIFA World Cup?', 'Italy', ['France', 'Germany', 'Brazil'], 'medium'),
  q('Which player was sent off for a headbutt in the 2006 World Cup final?', 'Zinedine Zidane', ['Thierry Henry', 'Marco Materazzi', 'Patrick Vieira'], 'easy'),
  q('Which country won the 2002 FIFA World Cup?', 'Brazil', ['Germany', 'France', 'Argentina'], 'easy'),
  q('The 2002 World Cup, the first held in Asia, was co-hosted by Japan and which other country?', 'South Korea', ['China', 'Thailand', 'Malaysia'], 'medium'),
  q('Who won the Golden Boot with 8 goals at the 2002 World Cup?', 'Ronaldo', ['Rivaldo', 'Miroslav Klose', 'Michael Ballack'], 'hard'),
  q('Who scored two headed goals for France in the 1998 World Cup final?', 'Zinedine Zidane', ['Thierry Henry', 'Emmanuel Petit', 'Youri Djorkaeff'], 'medium'),
  q('Which country did France beat 3-0 in the 1998 World Cup final?', 'Brazil', ['Italy', 'Croatia', 'Netherlands'], 'medium'),
  q('Which famous Italian striker missed the decisive penalty in the 1994 World Cup final shootout?', 'Roberto Baggio', ['Franco Baresi', 'Daniele Massaro', 'Paolo Maldini'], 'medium'),
  q('The 1994 World Cup final was the first ever decided by a penalty shootout. Who won it?', 'Brazil', ['Italy', 'Argentina', 'Germany'], 'medium'),
  q('Which country won the 1990 FIFA World Cup?', 'West Germany', ['Argentina', 'Italy', 'Brazil'], 'medium'),
  q('Which Italian striker was top scorer at the 1990 World Cup?', 'Salvatore Schillaci', ['Roberto Baggio', 'Gianluca Vialli', 'Paolo Rossi'], 'hard'),
  q('Diego Maradona captained which country to the 1986 World Cup?', 'Argentina', ['Brazil', 'Uruguay', 'Mexico'], 'easy'),
  q('Against which country did Maradona score the "Hand of God" goal in 1986?', 'England', ['Italy', 'West Germany', 'Belgium'], 'easy'),
  q('Which Italian striker was top scorer as Italy won the 1982 World Cup?', 'Paolo Rossi', ['Alessandro Altobelli', 'Marco Tardelli', 'Dino Zoff'], 'hard'),
  q('Pelé won his third World Cup with Brazil in which year?', '1970', ['1966', '1974', '1962'], 'medium'),
  q('Which country won the World Cup on home soil at Wembley in 1966?', 'England', ['West Germany', 'Brazil', 'Portugal'], 'easy'),
  q('Who scored a hat-trick in the 1966 World Cup final?', 'Geoff Hurst', ['Bobby Charlton', 'Martin Peters', 'Jimmy Greaves'], 'medium'),
  q('A 17-year-old Pelé won his first World Cup with Brazil in which year?', '1958', ['1962', '1954', '1950'], 'medium'),
  q('Which Frenchman scored a record 13 goals at a single World Cup in 1958?', 'Just Fontaine', ['Raymond Kopa', 'Michel Platini', 'Thierry Henry'], 'hard'),
  q('The "Maracanazo" refers to which country shocking Brazil in the deciding match of the 1950 World Cup?', 'Uruguay', ['Argentina', 'Chile', 'Paraguay'], 'hard'),
  q('The "Miracle of Bern" was West Germany beating which team in the 1954 World Cup final?', 'Hungary', ['Brazil', 'Austria', 'Uruguay'], 'hard'),
  q('Who is the all-time top scorer in World Cup history with 16 goals?', 'Miroslav Klose', ['Ronaldo', 'Pelé', 'Gerd Müller'], 'medium'),
  q('Which is the only country to have played in every World Cup tournament?', 'Brazil', ['Germany', 'Italy', 'Argentina'], 'medium'),
  q('What was the original World Cup trophy called?', 'The Jules Rimet Trophy', ['The Henri Delaunay Trophy', 'The Golden Globe', 'The FIFA Cup'], 'medium'),
  q('How many countries are co-hosting the 2026 World Cup?', '3', ['2', '1', '4'], 'easy'),
  q('How many teams play in the 2026 World Cup, the biggest ever?', '48', ['32', '40', '64'], 'medium'),
  q('Who won the Golden Boot at the 2018 World Cup?', 'Harry Kane', ['Kylian Mbappé', 'Antoine Griezmann', 'Romelu Lukaku'], 'medium'),
  q('Who won the Golden Boot at the 2022 World Cup with 8 goals?', 'Kylian Mbappé', ['Lionel Messi', 'Olivier Giroud', 'Harry Kane'], 'medium'),
  q('Which nation became the first from Africa to reach a World Cup semi-final in 2022?', 'Morocco', ['Senegal', 'Ghana', 'Cameroon'], 'medium'),
  q('Which Cameroonian became the oldest World Cup goalscorer at 42 in 1994?', 'Roger Milla', ['Samuel Eto’o', 'Patrick Mboma', 'Thomas N’Kono'], 'hard'),
  q('Which nation became the first from Africa to reach a World Cup quarter-final in 1990?', 'Cameroon', ['Nigeria', 'Egypt', 'Morocco'], 'hard'),
  q('Which country won back-to-back World Cups in 1934 and 1938?', 'Italy', ['Uruguay', 'Brazil', 'Argentina'], 'hard'),
  q('England have won the World Cup how many times?', '1', ['2', '0', '3'], 'easy'),
  q('Spain’s only World Cup triumph came in which year?', '2010', ['2014', '2008', '2006'], 'easy'),
  q('Which Uruguayan won the Golden Ball as best player of the 2010 World Cup?', 'Diego Forlán', ['Luis Suárez', 'Edinson Cavani', 'Wesley Sneijder'], 'hard'),
  q('Which country won the 1962 World Cup held in Chile?', 'Brazil', ['Czechoslovakia', 'Chile', 'Italy'], 'hard'),
  q('How often is the FIFA World Cup held?', 'Every 4 years', ['Every 2 years', 'Every 3 years', 'Every 5 years'], 'easy'),
  q('Which Portuguese legend was top scorer at the 1966 World Cup?', 'Eusébio', ['Cristiano Ronaldo', 'Luís Figo', 'Mário Coluna'], 'hard'),
]
