/**
 * Deals the question bank into levels and freezes the result.
 *
 *   npx tsx scripts/buildLevels.ts            # rewrite src/game/levels/levelIds.ts
 *   npx tsx scripts/buildLevels.ts --sql 1-1  # print level_questions seed rows for levels 1..1
 *
 * Append-only: levels already in levelIds.ts are kept exactly as they are, and
 * only bank questions that no level holds yet are dealt into new levels at the
 * end. Re-dealing existing levels would move solved questions between levels
 * and break saved progress plus the level_questions seed.
 */
import { existsSync } from 'node:fs'
import { writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { footballBank } from '../src/services/trivia/bank'
import { buildLevelIds } from '../src/game/levels/build'

const PER_LEVEL = 24
const HERE = dirname(fileURLToPath(import.meta.url))
const OUT = join(HERE, '..', 'src', 'game', 'levels', 'levelIds.ts')

async function frozenLevels(): Promise<string[][]> {
  if (!existsSync(OUT)) return []
  const mod = (await import(pathToFileURL(OUT).href)) as { LEVEL_IDS: string[][] }
  return mod.LEVEL_IDS
}

function render(levels: string[][]): string {
  const rows = levels.map((ids) => `  [${ids.map((id) => `'${id}'`).join(', ')}],`).join('\n')
  return `// Generated by scripts/buildLevels.ts. Append-only — never reorder or edit a
// level by hand; saved progress and the level_questions seed depend on it.
export const LEVEL_IDS: string[][] = [
${rows}
]
`
}

function seedSql(levels: string[][], from: number, to: number): string {
  const rows: string[] = []
  for (let n = from; n <= to; n++) {
    for (const id of levels[n - 1] ?? []) rows.push(`  ('${id}', ${n})`)
  }
  return `insert into level_questions (question_id, level) values\n${rows.join(',\n')}\non conflict (question_id) do nothing;`
}

const args = process.argv.slice(2)
const sqlAt = args.indexOf('--sql')
const existing = await frozenLevels()

if (sqlAt >= 0) {
  const [from, to] = (args[sqlAt + 1] ?? '1-1').split('-').map(Number)
  console.log(seedSql(existing, from, to ?? from))
} else {
  const taken = new Set(existing.flat())
  const fresh = buildLevelIds(
    footballBank.filter((q) => !taken.has(q.id)),
    PER_LEVEL,
  )
  const levels = [...existing, ...fresh]
  await writeFile(OUT, render(levels))
  console.log(`${levels.length} levels (${fresh.length} new) -> ${OUT}`)
}
